# Shell variables
# Generated by 'wal'
wallpaper='/home/Intrusionz3r0/Pictures/Data.jpg'

# Special
background='#1c1b26'
foreground='#f5c5c6'
cursor='#f5c5c6'

# Colors
color0='#1c1b26'
color1='#4F3C41'
color2='#A0090F'
color3='#DB1E22'
color4='#D04149'
color5='#F45B60'
color6='#F97D83'
color7='#f5c5c6'
color8='#ab898a'
color9='#4F3C41'
color10='#A0090F'
color11='#DB1E22'
color12='#D04149'
color13='#F45B60'
color14='#F97D83'
color15='#f5c5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
