#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

wmname LG3D &
vmware-user-suid-wrapper &
# La siguiente line ajusta la polybar a las dimenciones de la pantalla 1920x1080. desactiva este comentario si es necesario
xrandr --output Virtual1 --mode 1920x1080 --rate 60 &
bspc monitor -d I II III IV V VI VII VIII IX X
#$HOME/.config/bspwm/scripts/dual_monitor.sh

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config normal_border_color '#808080'
bspc config focused_border_color '#b80303'
bspc config presel_feedback_color '#512da8'

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-fill ~/Pictures/NetWatch.png &
~/.config/polybar/./launch.sh --shapes &
picom --config ~/.config/picom/picom.conf &
